function titlestr = getCOGtitle(xdata,ydata)
% takes input x/y data and returns title string while ignoring NaNs in
% input data

titlestr = sprintf('AVG_{x,y} %4.1f / %4.1f | STD_{x,y} %2.1f / %2.1f',...
    mean(xdata(~isnan(xdata))),...
    mean(ydata(~isnan(ydata))),...
    std(xdata(~isnan(xdata))),...
    std(ydata(~isnan(ydata))));
end

